version: '3.8'

services:
  wireguard:
    container_name: wireguard-alpine
    image: wireguard-alpine:1.0.0
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:30000:30000/udp"
